version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:410419084195:task-definition/hello-world-api-task:1"
        LoadBalancerInfo:
          ContainerName: "hello-world-rest-api"
          ContainerPort: "80"
        PlatformVersion: "LATEST"